version: "3"
services:
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres
    volumes:
#      - postgres-data:/var/lib/postgresql/data
      - ./db/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=foodanddrinks
      - POSTGRES_DB=foodanddrinks
    restart: unless-stopped
    networks:
      - mynet
  # APP*****************************************
  fadapp:
    image: fadapp:latest
    network_mode: bridge
    container_name: fadapp
    expose:
      - 8080
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - mynet
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  mynet:
    driver: bridge
volumes:
  postgres-data: